# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-02-24 02:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Extorsion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extorsion',
            name='phone',
            field=models.BigIntegerField(),
        ),
    ]
